version: '3'
services:
  api-personas-postgres:
    container_name: api-personas-postgres
    build: .
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres:root@postgres:5432
      PORT: 3000
      
    depends_on:
      - postgres
    links:
      - postgres


  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: personas